import { useState, useRef, useCallback } from 'react';

function formatDate(iso) {
  if (!iso) return '';
  try {
    return new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  } catch (_) { return ''; }
}

function safeNum(v) {
  return typeof v === 'number' && isFinite(v) ? v : 0;
}

function s(v) {
  if (v === null || v === undefined) return '';
  return String(v).replace(/[<>&"']/g, function (c) {
    return { '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&#39;' }[c];
  });
}

function typeColor(type) {
  if (type === 'backend') return '#10b981';
  if (type === 'infra') return '#f59e0b';
  return '#3b82f6';
}

function buildHtml(data, theme) {
  var isDark = theme === 'dark';
  var bg = isDark ? '#0f172a' : '#ffffff';
  var fg = isDark ? '#f1f5f9' : '#111111';
  var muted = isDark ? '#94a3b8' : '#6b7280';
  var dim = isDark ? '#64748b' : '#9ca3af';
  var cardBg = isDark ? '#1e293b' : '#f8fafc';
  var border = isDark ? '#334155' : '#e5e7eb';
  var accent = '#c5fb45';
  var red = '#ef4444';

  var total = safeNum(data.summary?.total);
  var cats = safeNum(data.summary?.categories);
  var fe = safeNum(data.summary?.frontend);
  var be = safeNum(data.summary?.backend);
  var inf = safeNum(data.summary?.infra);

  var html = '';
  html += '<div style="font-family:Helvetica,Arial,sans-serif;color:' + fg + ';background:' + bg + ';padding:0;margin:0;width:794px;">';

  // ─── COVER ───
  html += '<div style="height:1122px;position:relative;overflow:hidden;background:linear-gradient(180deg,#0f172a,#1e293b);">';
  html += '<div style="position:absolute;top:55px;left:20px;width:3px;height:40px;background:' + accent + ';"></div>';
  html += '<div style="position:absolute;top:58px;left:30px;font-size:10px;font-weight:bold;color:' + accent + ';letter-spacing:2px;">TECHSTACK FINDER</div>';
  html += '<div style="position:absolute;top:78px;left:30px;font-size:36px;font-weight:bold;color:#fff;">Technology Report</div>';
  html += '<div style="position:absolute;top:120px;left:30px;font-size:18px;color:#cbd5e1;">' + s(data.site?.domain || 'Unknown') + '</div>';
  var metaLine = [];
  if (data.site?.scannedAt) metaLine.push(formatDate(data.site.scannedAt));
  if (data.site?.statusCode) metaLine.push('HTTP ' + data.site.statusCode);
  metaLine.push((data.categories?.length || 0) + ' categories');
  metaLine.push(total + ' technologies');
  html += '<div style="position:absolute;top:148px;left:30px;font-size:10px;color:' + dim + ';">' + s(metaLine.join('  ·  ')) + '</div>';

  // Stat cards
  var cardPositions = [30, 204, 378, 552];
  var cardWidths = 154;
  var cardLabels = ['Technologies', 'Categories', 'Frontend', 'Backend+Infra'];
  var cardValues = [total, cats, total ? Math.round((fe / total) * 100) + '%' : '0%', total ? Math.round(((be + inf) / total) * 100) + '%' : '0%'];
  var cardColors = [accent, '#3b82f6', '#3b82f6', '#10b981'];
  for (var ci = 0; ci < 4; ci++) {
    html += '<div style="position:absolute;top:200px;left:' + cardPositions[ci] + 'px;width:' + cardWidths + 'px;height:70px;background:' + cardBg + ';border:1px solid ' + border + ';border-radius:8px;">';
    html += '<div style="padding:12px 16px;">';
    html += '<div style="font-size:24px;font-weight:bold;color:' + cardColors[ci] + ';">' + s(String(cardValues[ci])) + '</div>';
    html += '<div style="font-size:8px;color:' + muted + ';text-transform:uppercase;margin-top:4px;">' + s(cardLabels[ci]) + '</div>';
    html += '</div></div>';
  }

  // Footer
  html += '<div style="position:absolute;bottom:30px;left:20px;right:20px;font-size:8px;color:' + dim + ';display:flex;justify-content:space-between;">';
  html += '<span>Generated by TechStack Finder</span><span>' + s(formatDate(new Date().toISOString())) + '</span>';
  html += '</div>';
  html += '</div>';

  // ─── STACK DISTRIBUTION ───
  html += '<div style="page-break-before:always;padding:20px;">';
  html += '<div style="margin-bottom:16px;"><span style="display:inline-block;width:3px;height:20px;background:' + accent + ';vertical-align:middle;margin-right:8px;"></span><span style="font-size:16px;font-weight:bold;">Stack Distribution</span></div>';

  // Bar
  html += '<div style="display:flex;height:20px;border-radius:10px;overflow:hidden;background:' + border + ';margin-bottom:8px;">';
  if (total > 0 && fe > 0) html += '<div style="width:' + Math.round((fe / total) * 100) + '%;background:#3b82f6;"></div>';
  if (total > 0 && be > 0) html += '<div style="width:' + Math.round((be / total) * 100) + '%;background:#10b981;"></div>';
  if (total > 0 && inf > 0) html += '<div style="width:' + Math.round((inf / total) * 100) + '%;background:#f59e0b;"></div>';
  html += '</div>';

  // Legend
  html += '<div style="font-size:11px;margin-bottom:24px;">';
  html += '<span style="display:inline-block;width:10px;height:10px;background:#3b82f6;border-radius:2px;vertical-align:middle;margin-right:4px;"></span>Frontend ' + (total ? Math.round((fe / total) * 100) : 0) + '% (' + fe + ') &nbsp;&nbsp;';
  html += '<span style="display:inline-block;width:10px;height:10px;background:#10b981;border-radius:2px;vertical-align:middle;margin-right:4px;"></span>Backend ' + (total ? Math.round((be / total) * 100) : 0) + '% (' + be + ') &nbsp;&nbsp;';
  html += '<span style="display:inline-block;width:10px;height:10px;background:#f59e0b;border-radius:2px;vertical-align:middle;margin-right:4px;"></span>Infra ' + (total ? Math.round((inf / total) * 100) : 0) + '% (' + inf + ')';
  html += '</div>';

  // ─── CATEGORY BREAKDOWN ───
  var catStats = [];
  (data.categories || []).forEach(function (c) {
    if (c.technologies && c.technologies.length > 0) {
      catStats.push({ name: c.category, count: c.technologies.length });
    }
  });
  catStats.sort(function (a, b) { return b.count - a.count; });

  if (catStats.length > 0) {
    html += '<div style="margin-bottom:16px;"><span style="display:inline-block;width:3px;height:20px;background:#3b82f6;vertical-align:middle;margin-right:8px;"></span><span style="font-size:16px;font-weight:bold;">Category Breakdown</span></div>';
    var maxCount = catStats[0].count;
    html += '<div style="display:flex;flex-wrap:wrap;gap:8px;margin-bottom:24px;">';
    for (var csi = 0; csi < Math.min(catStats.length, 20); csi++) {
      var cs = catStats[csi];
      var pct = Math.round((cs.count / maxCount) * 100);
      html += '<div style="width:calc(50% - 4px);margin-bottom:8px;">';
      html += '<div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:3px;"><span style="font-weight:bold;">' + s(cs.name) + '</span><span style="color:' + muted + ';">' + cs.count + '</span></div>';
      html += '<div style="height:8px;border-radius:4px;background:' + border + ';overflow:hidden;">';
      html += '<div style="width:' + pct + '%;height:100%;background:' + accent + ';border-radius:4px;"></div>';
      html += '</div></div>';
    }
    html += '</div>';
  }

  // ─── TECHNOLOGIES ───
  var allTechs = [];
  (data.categories || []).forEach(function (cat) {
    (cat.technologies || []).forEach(function (t) {
      allTechs.push({ name: t.name, version: t.version, type: t.type, confidence: t.confidence, detectedVia: t.detectedVia, categoryName: cat.category });
    });
  });

  if (allTechs.length > 0) {
    html += '<div style="margin-bottom:16px;"><span style="display:inline-block;width:3px;height:20px;background:#10b981;vertical-align:middle;margin-right:8px;"></span><span style="font-size:16px;font-weight:bold;">Technology Details</span></div>';
    html += '<div style="display:flex;flex-wrap:wrap;gap:8px;">';
    for (var ai = 0; ai < allTechs.length; ai++) {
      var tech = allTechs[ai];
      var tc = typeColor(tech.type);
      var confPct = tech.confidence === 'high' ? 95 : tech.confidence === 'medium' ? 65 : 35;
      html += '<div style="width:calc(50% - 4px);border:1px solid ' + border + ';border-radius:8px;padding:12px;background:' + cardBg + ';margin-bottom:4px;">';
      html += '<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px;">';
      html += '<div><span style="font-size:13px;font-weight:bold;">' + s(tech.name) + '</span>';
      if (tech.version) html += ' <span style="font-size:11px;color:' + dim + ';">v' + s(tech.version) + '</span>';
      html += '</div>';
      html += '<span style="font-size:9px;font-weight:bold;color:#fff;background:' + tc + ';padding:2px 8px;border-radius:10px;">' + s((tech.type || 'frontend').toUpperCase()) + '</span>';
      html += '</div>';
      html += '<div style="font-size:10px;color:' + muted + ';margin-bottom:6px;">' + s(tech.categoryName || '') + ' via <span style="color:' + fg + ';">' + s(tech.detectedVia || '') + '</span></div>';
      html += '<div style="height:6px;border-radius:3px;background:' + border + ';overflow:hidden;">';
      html += '<div style="width:' + confPct + '%;height:100%;background:' + tc + ';border-radius:3px;"></div>';
      html += '</div></div>';
    }
    html += '</div>';
  }

  // ─── SEO ───
  if (data.seo) {
    html += '<div style="page-break-before:always;padding:20px 0;">';
    html += '<div style="margin-bottom:16px;"><span style="display:inline-block;width:3px;height:20px;background:#f59e0b;vertical-align:middle;margin-right:8px;"></span><span style="font-size:16px;font-weight:bold;">SEO Analysis</span></div>';

    var seoScore = safeNum(data.seo.score);
    var seoClr = seoScore >= 80 ? '#10b981' : seoScore >= 50 ? '#f59e0b' : red;
    html += '<div style="display:flex;gap:8px;margin-bottom:16px;">';
    html += '<div style="flex:1;background:' + cardBg + ';border:1px solid ' + border + ';border-radius:8px;padding:16px;text-align:center;"><div style="font-size:28px;font-weight:bold;color:' + seoClr + ';">' + s(String(seoScore || '-')) + '</div><div style="font-size:9px;color:' + muted + ';text-transform:uppercase;">SCORE</div></div>';
    html += '<div style="flex:1;background:' + cardBg + ';border:1px solid ' + border + ';border-radius:8px;padding:16px;text-align:center;"><div style="font-size:28px;font-weight:bold;color:' + seoClr + ';">' + s(data.seo.grade || '-') + '</div><div style="font-size:9px;color:' + muted + ';text-transform:uppercase;">GRADE</div></div>';
    html += '<div style="flex:1;background:' + cardBg + ';border:1px solid ' + border + ';border-radius:8px;padding:16px;text-align:center;"><div style="font-size:28px;font-weight:bold;color:#3b82f6;">H1:' + safeNum(data.seo.headings?.h1) + ' H2:' + safeNum(data.seo.headings?.h2) + '</div><div style="font-size:9px;color:' + muted + ';text-transform:uppercase;">HEADINGS</div></div>';
    html += '</div>';

    if (data.seo.title?.text) html += '<div style="margin-bottom:8px;"><div style="font-size:9px;color:' + dim + ';text-transform:uppercase;margin-bottom:2px;">TITLE</div><div style="font-size:12px;">' + s(data.seo.title.text) + '</div></div>';
    if (data.seo.description?.text) html += '<div style="margin-bottom:8px;"><div style="font-size:9px;color:' + dim + ';text-transform:uppercase;margin-bottom:2px;">DESCRIPTION</div><div style="font-size:12px;color:' + muted + ';">' + s(data.seo.description.text) + '</div></div>';
    html += '</div>';
  }

  // ─── PERFORMANCE ───
  if (data.performance) {
    html += '<div style="margin-bottom:16px;"><span style="display:inline-block;width:3px;height:20px;background:#10b981;vertical-align:middle;margin-right:8px;"></span><span style="font-size:16px;font-weight:bold;">Performance</span></div>';
    var perf = data.performance;
    html += '<div style="display:flex;flex-wrap:wrap;gap:8px;margin-bottom:24px;">';
    var perfItems = [
      ['HTTPS', perf.isHttps ? 'Enabled' : 'Not detected'],
      ['Compression', perf.compression],
      ['Cache Control', perf.cacheControl],
      ['HTTP Version', perf.httpVersion],
      ['Keep-Alive', perf.keepAlive],
      ['Alt-Svc', perf.altSvc],
    ];
    for (var pi = 0; pi < perfItems.length; pi++) {
      if (!perfItems[pi][1]) continue;
      html += '<div style="width:calc(33.33% - 6px);background:' + cardBg + ';border:1px solid ' + border + ';border-radius:8px;padding:12px;">';
      html += '<div style="font-size:9px;color:' + dim + ';text-transform:uppercase;margin-bottom:4px;">' + s(perfItems[pi][0]) + '</div>';
      html += '<div style="font-size:12px;font-weight:bold;">' + s(perfItems[pi][1]) + '</div></div>';
    }
    html += '</div>';
  }

  // ─── SECURITY ───
  if (data.security) {
    html += '<div style="margin-bottom:16px;"><span style="display:inline-block;width:3px;height:20px;background:' + red + ';vertical-align:middle;margin-right:8px;"></span><span style="font-size:16px;font-weight:bold;">Security Headers</span></div>';
    var sec = data.security;
    var secItems = [
      ['Content-Security-Policy', sec.contentSecurityPolicy],
      ['Strict-Transport-Security', sec.strictTransportSecurity],
      ['X-Frame-Options', sec.xFrameOptions],
      ['X-Content-Type-Options', sec.xContentTypeOptions],
      ['Referrer-Policy', sec.referrerPolicy],
      ['Permissions-Policy', sec.permissionsPolicy],
      ['X-XSS-Protection', sec.xssProtection],
      ['CORS', sec.cors?.allowOrigin],
    ];
    html += '<div style="margin-bottom:24px;">';
    for (var si = 0; si < secItems.length; si++) {
      if (!secItems[si][1]) continue;
      html += '<div style="margin-bottom:8px;padding:8px 12px;background:' + cardBg + ';border:1px solid ' + border + ';border-radius:6px;">';
      html += '<div style="font-size:9px;color:' + dim + ';text-transform:uppercase;margin-bottom:2px;">' + s(secItems[si][0]) + '</div>';
      html += '<div style="font-size:11px;word-break:break-all;">' + s(secItems[si][1]) + '</div></div>';
    }
    html += '</div>';
  }

  // ─── RESPONSE HEADERS ───
  if (data.responseHeaders && Object.keys(data.responseHeaders).length > 0) {
    html += '<div style="page-break-before:always;padding:20px 0;">';
    html += '<div style="margin-bottom:16px;"><span style="display:inline-block;width:3px;height:20px;background:#8b5cf6;vertical-align:middle;margin-right:8px;"></span><span style="font-size:16px;font-weight:bold;">Response Headers</span></div>';
    html += '<div style="margin-bottom:24px;">';
    var rhKeys = Object.keys(data.responseHeaders).slice(0, 20);
    for (var ri = 0; ri < rhKeys.length; ri++) {
      var rv = data.responseHeaders[rhKeys[ri]];
      var rvStr = Array.isArray(rv) ? rv.join(', ') : String(rv);
      html += '<div style="display:flex;margin-bottom:4px;font-size:11px;">';
      html += '<div style="width:200px;font-weight:bold;color:' + muted + ';">' + s(rhKeys[ri]) + '</div>';
      html += '<div style="flex:1;word-break:break-all;">' + s(rvStr) + '</div></div>';
    }
    html += '</div></div>';
  }

  // ─── PAGE METADATA ───
  if (data.pageMetadata) {
    html += '<div style="margin-bottom:16px;"><span style="display:inline-block;width:3px;height:20px;background:#6366f1;vertical-align:middle;margin-right:8px;"></span><span style="font-size:16px;font-weight:bold;">Page Metadata</span></div>';
    var md = data.pageMetadata;
    var mdItems = [
      ['Title', md.title], ['Description', md.description], ['Canonical', md.canonical],
      ['Robots', md.robots], ['Language', md.language], ['Author', md.author],
      ['OG Title', md.ogTitle], ['OG Description', md.ogDescription], ['OG Image', md.ogImage],
      ['Twitter Card', md.twitterCard], ['Twitter Site', md.twitterSite],
      ['Favicon', md.favicon], ['Manifest', md.manifest], ['Theme Color', md.themeColor],
    ];
    html += '<div style="margin-bottom:24px;">';
    for (var mi = 0; mi < mdItems.length; mi++) {
      if (!mdItems[mi][1]) continue;
      html += '<div style="margin-bottom:6px;padding:6px 12px;background:' + cardBg + ';border:1px solid ' + border + ';border-radius:6px;">';
      html += '<div style="font-size:9px;color:' + dim + ';text-transform:uppercase;margin-bottom:2px;">' + s(mdItems[mi][0]) + '</div>';
      html += '<div style="font-size:11px;word-break:break-all;">' + s(mdItems[mi][1]) + '</div></div>';
    }
    html += '</div>';
  }

  // ─── COMPANY ───
  if (data.company && data.company.name) {
    html += '<div style="margin-bottom:16px;"><span style="display:inline-block;width:3px;height:20px;background:#8b5cf6;vertical-align:middle;margin-right:8px;"></span><span style="font-size:16px;font-weight:bold;">Company Profile</span></div>';
    html += '<div style="background:' + cardBg + ';border:1px solid ' + border + ';border-radius:8px;padding:16px;margin-bottom:24px;">';
    html += '<div style="font-size:18px;font-weight:bold;margin-bottom:8px;">' + s(data.company.name) + '</div>';
    if (data.company.description) html += '<div style="font-size:12px;color:' + muted + ';margin-bottom:12px;">' + s(data.company.description) + '</div>';
    var coItems = [['Industry', data.company.industry], ['Founded', data.company.foundingDate], ['Employees', data.company.employeeCount]];
    for (var coi = 0; coi < coItems.length; coi++) {
      if (!coItems[coi][1]) continue;
      html += '<div style="display:inline-block;margin-right:24px;"><div style="font-size:9px;color:' + dim + ';text-transform:uppercase;">' + s(coItems[coi][0]) + '</div><div style="font-size:12px;font-weight:bold;">' + s(coItems[coi][1]) + '</div></div>';
    }
    html += '</div>';
  }

  // Footer
  html += '<div style="text-align:center;padding:16px;font-size:9px;color:' + dim + ';border-top:1px solid ' + border + ';">TechStack Finder · Full-stack technology detection engine</div>';
  html += '</div>';

  return html;
}

export default function DownloadPdfButton({ data, fileName = 'report' }) {
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState(null);
  const [pdfTheme, setPdfTheme] = useState('dark');
  const containerRef = useRef(null);
  const jsPDFRef = useRef(null);

  const handleDownload = useCallback(async () => {
    if (!data || generating) return;
    setGenerating(true);
    setError(null);

    try {
      if (!jsPDFRef.current) {
        var mod = await import('jspdf');
        jsPDFRef.current = mod.jsPDF;
      }
      var jsPDF = jsPDFRef.current;
      var html2canvasMod = await import('html2canvas');
      var html2canvas = html2canvasMod.default;

      var container = containerRef.current;
      if (!container) { throw new Error('PDF container not mounted'); }

      var htmlContent = buildHtml(data, pdfTheme);
      container.innerHTML = htmlContent;

      // Make visible for capture
      container.style.left = '0px';
      container.style.top = '0px';
      container.style.zIndex = '-1';
      container.style.opacity = '1';
      container.style.position = 'fixed';

      await new Promise(function (r) { setTimeout(r, 200); });

      var canvas = await html2canvas(container, {
        scale: 2,
        useCORS: true,
        logging: false,
        width: 794,
        backgroundColor: null,
      });

      // Hide again
      container.style.left = '-9999px';
      container.style.position = 'absolute';
      container.style.zIndex = '';
      container.style.opacity = '';

      var imgW = canvas.width;
      var imgH = canvas.height;
      var pdfW = 210;
      var pdfH = 297;
      var marginMm = 0;
      var usableW = pdfW - marginMm * 2;
      var pxPerMm = imgW / usableW;
      var pageHpx = (pdfH - marginMm * 2) * pxPerMm;

      var totalPages = Math.ceil(imgH / pageHpx);
      var pdf = new jsPDF('p', 'mm', 'a4');

      for (var p = 0; p < totalPages; p++) {
        if (p > 0) pdf.addPage();
        var srcY = p * pageHpx;
        var srcH = Math.min(pageHpx, imgH - srcY);

        var pageCanvas = document.createElement('canvas');
        pageCanvas.width = imgW;
        pageCanvas.height = srcH;
        var ctx = pageCanvas.getContext('2d');
        ctx.drawImage(canvas, 0, srcY, imgW, srcH, 0, 0, imgW, srcH);

        var imgData = pageCanvas.toDataURL('image/jpeg', 0.92);
        var destH = srcH / pxPerMm;
        pdf.addImage(imgData, 'JPEG', marginMm, marginMm, usableW, destH);
      }

      var blob = pdf.output('blob');
      var url = URL.createObjectURL(blob);
      var a = document.createElement('a');
      a.href = url;
      a.download = (fileName.replace(/[^a-z0-9]/gi, '-') || 'report') + '-techstack-report-' + pdfTheme + '.pdf';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(function () { URL.revokeObjectURL(url); }, 1000);
    } catch (err) {
      console.error('PDF generation failed:', err);
      setError(err.message || 'PDF generation failed');
    } finally {
      setGenerating(false);
    }
  }, [data, pdfTheme, fileName, generating]);

  return (
    <div className="flex flex-col items-start gap-2">
      <div className="flex items-center gap-2">
        <button
          onClick={handleDownload}
          disabled={generating || !data}
          className="flex items-center gap-3 rounded-xl border border-accent/30 bg-accent/10 px-6 py-3 font-mono text-sm font-semibold text-accent hover:bg-accent/20 hover:border-accent/50 transition-all duration-300 disabled:opacity-40"
        >
          {generating ? (
            <>
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-accent/40 border-t-accent" />
              Generating PDF…
            </>
          ) : (
            <>
              <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Download PDF
            </>
          )}
        </button>
        <button
          onClick={() => setPdfTheme(pdfTheme === 'dark' ? 'light' : 'dark')}
          className="flex items-center gap-1.5 rounded-lg border border-border bg-elevated px-3 py-3 text-xs text-muted hover:border-border-strong hover:text-fg transition-colors"
          title={`Switch to ${pdfTheme === 'dark' ? 'light' : 'dark'} theme PDF`}
        >
          {pdfTheme === 'dark' ? (
            <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7">
              <circle cx="12" cy="12" r="5" />
              <path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42" />
            </svg>
          ) : (
            <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7">
              <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
            </svg>
          )}
        </button>
      </div>
      {error && (
        <p className="max-w-xs text-xs text-red-400">{error}</p>
      )}
      <div
        ref={containerRef}
        style={{ position: 'fixed', left: '-9999px', top: 0, width: '794px', background: '#0f172a', color: '#f1f5f9', zIndex: -1 }}
        aria-hidden="true"
      />
    </div>
  );
}
