'use client';
import { useState } from 'react';
import DownloadPdfButton from './DownloadPdfButton';

function downloadFile(content, fileName, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function flattenToCsv(data) {
  const rows = [['Category', 'Technology', 'Version', 'Type', 'Confidence', 'Detected Via']];
  (data.categories || []).forEach((cat) => {
    (cat.technologies || []).forEach((t) => {
      rows.push([cat.category, t.name, t.version || '', t.type || '', t.confidence || '', t.detectedVia || '']);
    });
  });
  return rows.map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
}

function buildHtmlReport(data) {
  const techRows = (data.categories || []).map((cat) => `
    <tr><td colspan="6" style="background:#1a1a1e;color:#c5fb45;font-weight:600;padding:8px">${cat.category}</td></tr>
    ${(cat.technologies || []).map((t) => `
      <tr>
        <td style="padding:6px 8px;border-bottom:1px solid #222">${t.name}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #222">${t.version || '-'}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #222">${t.type || '-'}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #222;text-transform:capitalize">${t.confidence || '-'}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #222">${t.detectedVia || '-'}</td>
      </tr>
    `).join('')}
  `).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>TechStack Report - ${data.site?.domain || 'Report'}</title>
<style>body{font-family:system-ui,sans-serif;background:#08080a;color:#f4f4ee;max-width:900px;margin:0 auto;padding:24px}
h1{font-size:24px;color:#c5fb45}table{width:100%;border-collapse:collapse;margin-top:16px}
th{text-align:left;padding:8px;border-bottom:2px solid #333;color:#9a9aa0;font-size:12px;text-transform:uppercase;letter-spacing:0.5px}
.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;margin:16px 0}
.stat{border:1px solid #222;border-radius:8px;padding:12px;background:#0c0c10}
.stat-label{font-size:11px;color:#9a9aa0}.stat-value{font-size:20px;font-weight:700;color:#f4f4ee}
.footer{margin-top:32px;padding-top:16px;border-top:1px solid #222;font-size:11px;color:#54545a}
</style></head><body>
<h1>TechStack Report: ${data.site?.domain || 'N/A'}</h1>
<p style="color:#9a9aa0">Scanned at ${data.site?.scannedAt || new Date().toISOString()} &middot; ${data.summary?.total || 0} technologies found</p>
<div class="summary">
  <div class="stat"><div class="stat-label">Health Score</div><div class="stat-value">${data.healthScore || '-'}</div></div>
  <div class="stat"><div class="stat-label">Total Technologies</div><div class="stat-value">${data.summary?.total || 0}</div></div>
  <div class="stat"><div class="stat-label">Frontend</div><div class="stat-value">${data.summary?.frontend || 0}</div></div>
  <div class="stat"><div class="stat-label">Backend</div><div class="stat-value">${data.summary?.backend || 0}</div></div>
  <div class="stat"><div class="stat-label">Infrastructure</div><div class="stat-value">${data.summary?.infra || 0}</div></div>
  <div class="stat"><div class="stat-label">Categories</div><div class="stat-value">${data.summary?.categories || 0}</div></div>
</div>
<table><thead><tr><th>Technology</th><th>Version</th><th>Type</th><th>Confidence</th><th>Detected Via</th></tr></thead><tbody>${techRows}</tbody></table>
<div class="footer">Generated by TechStack Finder &middot; Powered by opencode</div>
</body></html>`;
}

export default function ExportDashboard({ data, fileName = 'report' }) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleExport = (format) => {
    switch (format) {
      case 'csv':
        downloadFile(flattenToCsv(data), `${fileName}.csv`, 'text/csv');
        break;
      case 'json':
        downloadFile(JSON.stringify(data, null, 2), `${fileName}.json`, 'application/json');
        break;
      case 'html':
        downloadFile(buildHtmlReport(data), `${fileName}.html`, 'text/html');
        break;
      case 'copy-json':
        navigator.clipboard.writeText(JSON.stringify(data, null, 2)).then(() => {
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
        });
        break;
    }
    setOpen(false);
  };

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="flex items-center gap-2 rounded-lg border border-[var(--accent)]/25 bg-[var(--accent)]/10 px-3 py-1.5 text-xs font-medium text-[var(--accent)] transition-all duration-300 hover:bg-[var(--accent)]/20 active:scale-95"
      >
        <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3" />
        </svg>
        Export
      </button>

      {open && (
        <>
          <div className="fixed inset-0 z-[9998] bg-black/60 backdrop-blur-sm" onClick={() => setOpen(false)} />
          <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4">
            <div className="animate-fade-up mx-auto w-full max-w-sm rounded-2xl border border-white/[0.08] bg-[#0c0c10] p-6 shadow-[0_32px_64px_-16px_rgba(0,0,0,0.6)]">
              <div className="mb-4 flex items-center justify-between">
                <h3 className="text-lg font-semibold">Export scan data</h3>
                <button onClick={() => setOpen(false)} className="text-muted hover:text-fg">
                  <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M18 6L6 18M6 6l12 12" /></svg>
                </button>
              </div>
              <p className="mb-4 text-xs text-muted">Download or copy the full scan report for {data.site?.domain || fileName}</p>
              <div className="grid grid-cols-2 gap-3">
                <button onClick={() => handleExport('csv')} className="flex flex-col items-center gap-2 rounded-xl border border-white/[0.06] bg-white/[0.03] px-4 py-5 transition-all duration-300 hover:border-accent/20 hover:bg-accent/5 active:scale-95">
                  <svg className="h-5 w-5 text-muted" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6" /></svg>
                  <span className="text-xs font-medium">CSV</span>
                  <span className="text-[10px] text-muted">Spreadsheet</span>
                </button>
                <button onClick={() => handleExport('json')} className="flex flex-col items-center gap-2 rounded-xl border border-white/[0.06] bg-white/[0.03] px-4 py-5 transition-all duration-300 hover:border-accent/20 hover:bg-accent/5 active:scale-95">
                  <svg className="h-5 w-5 text-muted" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6" /></svg>
                  <span className="text-xs font-medium">JSON</span>
                  <span className="text-[10px] text-muted">Raw data</span>
                </button>
                <button onClick={() => handleExport('html')} className="flex flex-col items-center gap-2 rounded-xl border border-white/[0.06] bg-white/[0.03] px-4 py-5 transition-all duration-300 hover:border-accent/20 hover:bg-accent/5 active:scale-95">
                  <svg className="h-5 w-5 text-muted" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /></svg>
                  <span className="text-xs font-medium">HTML</span>
                  <span className="text-[10px] text-muted">Report</span>
                </button>
                <button onClick={() => handleExport('copy-json')} className="flex flex-col items-center gap-2 rounded-xl border border-white/[0.06] bg-white/[0.03] px-4 py-5 transition-all duration-300 hover:border-accent/20 hover:bg-accent/5 active:scale-95">
                  <svg className="h-5 w-5 text-muted" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><rect x="9" y="9" width="13" height="13" rx="2" ry="2" /><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" /></svg>
                  <span className="text-xs font-medium">{copied ? 'Copied!' : 'Copy JSON'}</span>
                  <span className="text-[10px] text-muted">Clipboard</span>
                </button>
              </div>
              <div className="mt-3">
                <DownloadPdfButton data={data} fileName={fileName} />
              </div>
            </div>
          </div>
        </>
      )}
    </>
  );
}
