'use client';
import { useState } from 'react';

export default function WhiteLabelPdf({ data }) {
  const [brandName, setBrandName] = useState('');
  const [accentColor, setAccentColor] = useState('#8b5cf6');
  const [logoUrl, setLogoUrl] = useState('');
  const [showPreview, setShowPreview] = useState(false);

  if (!data) return null;

  const generate = () => {
    const cats = (data.categories || []).map((cat) => {
      const techRows = cat.technologies.map((t) => `
        <tr>
          <td style="padding:8px 12px;border-bottom:1px solid #1e293b;font-size:13px;color:#e2e8f0">${t.name}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #1e293b;font-size:12px;color:#94a3b8;text-transform:uppercase">${t.type}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #1e293b;font-size:12px;color:#94a3b8">${t.confidence || 'medium'}</td>
        </tr>`).join('');
      return `
        <div style="margin-top:24px">
          <h3 style="font-size:14px;font-weight:600;color:${accentColor};margin-bottom:8px;text-transform:uppercase;letter-spacing:0.05em">${cat.category}</h3>
          <table style="width:100%;border-collapse:collapse;border:1px solid #1e293b;border-radius:8px;overflow:hidden">
            <thead><tr style="background:#0f172a">
              <th style="padding:8px 12px;text-align:left;font-size:11px;color:#64748b;text-transform:uppercase">Technology</th>
              <th style="padding:8px 12px;text-align:left;font-size:11px;color:#64748b;text-transform:uppercase">Type</th>
              <th style="padding:8px 12px;text-align:left;font-size:11px;color:#64748b;text-transform:uppercase">Confidence</th>
            </tr></thead>
            <tbody>${techRows}</tbody>
          </table>
        </div>`;
    }).join('');

    const html = `<!DOCTYPE html><html><head><style>
      body{font-family:system-ui,-apple-system,sans-serif;background:#0a0a0f;color:#f8fafc;padding:40px;margin:0}
      @media print{body{padding:20px}}
    </style></head><body>
      <div style="display:flex;align-items:center;gap:16px;margin-bottom:32px;padding-bottom:24px;border-bottom:2px solid ${accentColor}">
        ${logoUrl ? `<img src="${logoUrl}" style="height:40px" onerror="this.style.display='none'" />` : ''}
        <div>
          <h1 style="font-size:24px;font-weight:700;margin:0;color:#f8fafc">${brandName || 'TechStack'} Report</h1>
          <p style="font-size:13px;color:#64748b;margin:4px 0 0">${data.site?.domain} — ${new Date().toLocaleDateString()}</p>
        </div>
      </div>
      <div style="display:flex;gap:16px;margin-bottom:32px">
        <div style="flex:1;background:#0f172a;border:1px solid #1e293b;border-radius:8px;padding:16px;text-align:center">
          <div style="font-size:28px;font-weight:700;color:${accentColor}">${data.summary?.total || 0}</div>
          <div style="font-size:11px;color:#64748b;text-transform:uppercase">Technologies</div>
        </div>
        <div style="flex:1;background:#0f172a;border:1px solid #1e293b;border-radius:8px;padding:16px;text-align:center">
          <div style="font-size:28px;font-weight:700;color:#3b82f6">${data.summary?.frontend || 0}</div>
          <div style="font-size:11px;color:#64748b;text-transform:uppercase">Frontend</div>
        </div>
        <div style="flex:1;background:#0f172a;border:1px solid #1e293b;border-radius:8px;padding:16px;text-align:center">
          <div style="font-size:28px;font-weight:700;color:#10b981">${data.summary?.backend || 0}</div>
          <div style="font-size:11px;color:#64748b;text-transform:uppercase">Backend</div>
        </div>
        <div style="flex:1;background:#0f172a;border:1px solid #1e293b;border-radius:8px;padding:16px;text-align:center">
          <div style="font-size:28px;font-weight:700;color:#f59e0b">${data.summary?.infra || 0}</div>
          <div style="font-size:11px;color:#64748b;text-transform:uppercase">Infrastructure</div>
        </div>
      </div>
      ${cats}
      <div style="margin-top:40px;padding-top:16px;border-top:1px solid #1e293b;text-align:center;font-size:10px;color:#475569">
        Generated by ${brandName || 'TechStack Finder'} — ${new Date().toISOString()}
      </div>
    </body></html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  };

  return (
    <div className="rounded-2xl border border-border bg-elevated p-5 animate-fade-up">
      <div className="mb-4 flex items-center gap-2">
        <svg className="h-4 w-4 text-accent" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7">
          <path d="M12 2L2 7l10 5 10-5-10-5z" />
          <path d="M2 17l10 5 10-5M2 12l10 5 10-5" />
        </svg>
        <h3 className="text-sm font-semibold uppercase tracking-wider text-faint">White-Label PDF</h3>
      </div>
      <div className="space-y-3">
        <div>
          <label className="mb-1 block text-[10px] uppercase tracking-wider text-faint">Brand Name</label>
          <input value={brandName} onChange={(e) => setBrandName(e.target.value)} placeholder="Your Agency" className="w-full rounded-xl border border-border bg-bg px-4 py-2 text-sm text-fg placeholder:text-faint focus:border-accent focus:outline-none" />
        </div>
        <div>
          <label className="mb-1 block text-[10px] uppercase tracking-wider text-faint">Accent Color</label>
          <div className="flex items-center gap-3">
            <input type="color" value={accentColor} onChange={(e) => setAccentColor(e.target.value)} className="h-8 w-8 cursor-pointer rounded-lg border border-border" />
            <input value={accentColor} onChange={(e) => setAccentColor(e.target.value)} className="flex-1 rounded-xl border border-border bg-bg px-4 py-2 font-mono text-sm text-fg focus:border-accent focus:outline-none" />
          </div>
        </div>
        <div>
          <label className="mb-1 block text-[10px] uppercase tracking-wider text-faint">Logo URL (optional)</label>
          <input value={logoUrl} onChange={(e) => setLogoUrl(e.target.value)} placeholder="https://your-logo.com/logo.png" className="w-full rounded-xl border border-border bg-bg px-4 py-2 text-sm text-fg placeholder:text-faint focus:border-accent focus:outline-none" />
        </div>
        <button onClick={generate} className="w-full rounded-xl bg-accent px-5 py-2.5 text-sm font-semibold text-bg hover:brightness-110">
          Generate White-Label Report
        </button>
      </div>
    </div>
  );
}
