// Market trends data for the Trends page and per-technology detail pages.
// Live-site counts are derived from W3Techs usage shares (survey of the top
// ~10 million sites, August 2026) applied to the ~98M-site global index, or
// retained from the curated public index where W3Techs does not track a tech;
// per-country figures are derived deterministically from the worldwide totals.

export const COUNTRIES = [
  { code: 'IN', flag: '🇮🇳', name: 'India' },
  { code: 'US', flag: '🇺🇸', name: 'United States' },
  { code: 'GB', flag: '🇬🇧', name: 'United Kingdom' },
  { code: 'DE', flag: '🇩🇪', name: 'Germany' },
  { code: 'CA', flag: '🇨🇦', name: 'Canada' },
  { code: 'AU', flag: '🇦🇺', name: 'Australia' },
  { code: 'BR', flag: '🇧🇷', name: 'Brazil' },
  { code: 'JP', flag: '🇯🇵', name: 'Japan' },
];

const COUNTRY_MULTIPLIERS = {
  US: 0.18,
  GB: 0.05,
  DE: 0.045,
  CA: 0.03,
  AU: 0.025,
  BR: 0.02,
  JP: 0.015,
};

export const SPOTLIGHT_TECHNOLOGIES = [
  {
    slug: 'mcp-model-context-protocol',
    name: 'MCP Model Context Protocol',
    liveSites: 12480,
    indianSites: 812,
    tags: ['AI', 'Developer Tools', 'API Management'],
    description:
      'The Model Context Protocol (MCP) is a proposed open standard for defining and exchanging the contextual information required for the operation and interpretation of machine learning models.',
  },
  {
    slug: 'openai-conversion-tracking',
    name: 'OpenAI Conversion Tracking',
    liveSites: 8931,
    indianSites: 640,
    tags: ['AI', 'Conversion Tracking', 'Ad Pixel Management'],
    description:
      'Ads manager platform tracking pixel from OpenAI, tracking conversions from ads within OpenAI conversations / products.',
  },
  {
    slug: 'x402',
    name: 'X402',
    liveSites: 3420,
    indianSites: 96,
    tags: ['Payments', 'Fintech', 'Developer Tools'],
    description:
      'X402 is an open standard for internet-native payments, designed to facilitate agentic transactions at scale.',
  },
];

export const TECH_DIRECTORY = [
  {
    slug: 'wordpress',
    name: 'WordPress',
    description: 'Open-source content management system powering blogs, business sites, and stores.',
    tags: ['Content Management System', 'Open Source', 'Blog', 'Simple Website Builder', 'Community CMS'],
    liveSites: 40376000,
    indianSites: 745900,
  },
  {
    slug: 'jquery',
    name: 'jQuery',
    description: 'Fast, small JavaScript library that simplifies HTML document traversal and manipulation.',
    tags: ['JavaScript Libraries and Functions'],
    liveSites: 65856000,
    indianSites: 1317100,
  },
  {
    slug: 'react',
    name: 'React',
    description: 'JavaScript library for building component-based user interfaces.',
    tags: ['JavaScript Libraries and Functions', 'Framework'],
    liveSites: 5978000,
    indianSites: 120000,
  },
  {
    slug: 'node-js',
    name: 'Node.js',
    description: 'JavaScript runtime built on Chrome V8 for building server-side applications.',
    tags: ['Frameworks'],
    liveSites: 6370000,
    indianSites: 127400,
  },
  {
    slug: 'python',
    name: 'Python',
    description: 'High-level programming language popular for web and data applications.',
    tags: ['Frameworks'],
    liveSites: 1176000,
    indianSites: 23520,
  },
  {
    slug: 'typescript',
    name: 'TypeScript',
    description: 'Typed superset of JavaScript that compiles to plain JavaScript.',
    tags: ['JavaScript Libraries and Functions', 'Framework'],
    liveSites: 1470000,
    indianSites: 29400,
  },
  {
    slug: 'docker',
    name: 'Docker',
    description: 'Platform for developing, shipping, and running applications in containers.',
    tags: ['Web Hosting Providers', 'Cloud Hosting'],
    liveSites: 1176000,
    indianSites: 23520,
  },
  {
    slug: 'bootstrap',
    name: 'Bootstrap',
    description: 'CSS framework for responsive, mobile-first front-end development.',
    tags: ['Frameworks', 'CSS'],
    liveSites: 13524000,
    indianSites: 270480,
  },
  {
    slug: 'cloudflare',
    name: 'Cloudflare',
    description: 'CDN and DNS provider with security and performance edge services.',
    tags: ['Web Hosting Providers'],
    liveSites: 23814000,
    indianSites: 476280,
  },
  {
    slug: 'postgresql',
    name: 'PostgreSQL',
    description: 'Open-source relational database management system.',
    tags: ['Database'],
    liveSites: 1960000,
    indianSites: 39200,
  },
  {
    slug: 'next-js',
    name: 'Next.js',
    description: 'React framework for server-rendered and static web applications.',
    tags: ['Frameworks'],
    liveSites: 3038000,
    indianSites: 60760,
  },
  {
    slug: 'vue-js',
    name: 'Vue.js',
    description: 'Progressive JavaScript framework for building user interfaces.',
    tags: ['JavaScript Libraries and Functions', 'Framework'],
    liveSites: 588000,
    indianSites: 11760,
  },
  {
    slug: 'tailwind-css',
    name: 'Tailwind CSS',
    description: 'Utility-first CSS framework for rapidly building custom designs.',
    tags: ['Frameworks', 'CSS'],
    liveSites: 294000,
    indianSites: 5880,
  },
  {
    slug: 'angular',
    name: 'Angular',
    description: 'TypeScript-based platform for building web applications.',
    tags: ['JavaScript Libraries and Functions', 'Framework'],
    liveSites: 196000,
    indianSites: 3920,
  },
  {
    slug: 'vercel',
    name: 'Vercel',
    description: 'Frontend cloud platform and hosting for Jamstack and Next.js sites.',
    tags: ['Web Hosting Providers'],
    liveSites: 1764000,
    indianSites: 35280,
  },
  {
    slug: 'mongodb',
    name: 'MongoDB',
    description: 'Document-oriented NoSQL database platform.',
    tags: ['Database'],
    liveSites: 980000,
    indianSites: 19600,
  },
  {
    slug: 'graphql',
    name: 'GraphQL',
    description: 'Query language and runtime for APIs.',
    tags: ['API Management', 'JavaScript Libraries and Functions'],
    liveSites: 980000,
    indianSites: 19600,
  },
  {
    slug: 'svelte',
    name: 'Svelte',
    description: 'Compiler-based JavaScript framework for building user interfaces.',
    tags: ['JavaScript Libraries and Functions', 'Framework'],
    liveSites: 98000,
    indianSites: 1960,
  },
  {
    slug: 'amazon',
    name: 'Amazon',
    description: 'Cloud hosting, cloud PaaS, and web infrastructure behind millions of sites.',
    tags: ['Web Hosting Providers', 'Cloud Hosting', 'Cloud PaaS'],
    liveSites: 4410000,
    indianSites: 69900,
  },
  {
    slug: 'google-adsense',
    name: 'Google Adsense',
    description: 'Contextual advertising network serving cost-per-click ads across the web.',
    tags: ['Advertising', 'Contextual Advertising', 'Ad Server'],
    liveSites: 43120000,
    indianSites: 812000,
  },
  {
    slug: 'google-analytics',
    name: 'Google Analytics',
    description: 'Audience measurement and web analytics for site traffic and behavior.',
    tags: ['Analytics and Tracking', 'Audience Measurement'],
    liveSites: 47138000,
    indianSites: 925400,
  },
  {
    slug: 'php',
    name: 'PHP',
    description: 'Server-side scripting language at the core of most of the web.',
    tags: ['Frameworks'],
    liveSites: 25451028,
    indianSites: 688469,
  },
  {
    slug: 'google-apps-for-business',
    name: 'Google Apps for Business',
    description: 'Business email hosting and productivity suite.',
    tags: ['Email Hosting Providers', 'Business Email Hosting'],
    liveSites: 20470024,
    indianSites: 365582,
  },
  {
    slug: 'wix',
    name: 'Wix',
    description: 'Hosted website builder for simple sites and eCommerce.',
    tags: ['Content Management System', 'Hosted Solution', 'Simple Website Builder', 'eCommerce Enabled', 'Blog'],
    liveSites: 4214000,
    indianSites: 38320,
  },
  {
    slug: 'shopify',
    name: 'Shopify',
    description: 'Hosted eCommerce platform and online store builder for SMB and enterprise.',
    tags: ['eCommerce', 'Hosted Solution', 'SMB Solution', 'Online Store Builder', 'No-code eCommerce'],
    liveSites: 5194000,
    indianSites: 97350,
  },
  {
    slug: 'woocommerce',
    name: 'WooCommerce',
    description: 'WordPress plugin / module turning any WordPress site into an eCommerce store.',
    tags: ['eCommerce', 'Non Platform', 'Plugin / Module'],
    liveSites: 6736694,
    indianSites: 181919,
  },
  {
    slug: 'aspnet',
    name: 'ASP.NET',
    description: 'Microsoft web framework for building dynamic websites and services.',
    tags: ['Frameworks'],
    liveSites: 4894638,
    indianSites: 118758,
  },
  {
    slug: 'cart-functionality',
    name: 'Cart Functionality',
    description: 'Generic shopping-cart functionality detected on eCommerce stores.',
    tags: ['eCommerce', 'Non Platform'],
    liveSites: 2718588,
    indianSites: 50245,
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    description: 'Payments processor powering checkouts and payment acceptance.',
    tags: ['Payment', 'Checkout Buttons', 'Payments Processor', 'Payment Acceptance'],
    liveSites: 2450000,
    indianSites: 9910,
  },
  {
    slug: 'angular-js',
    name: 'Angular JS',
    description: 'JavaScript framework for building dynamic single-page applications.',
    tags: ['JavaScript Libraries and Functions', 'Framework'],
    liveSites: 1074759,
    indianSites: 19030,
  },
  {
    slug: 'mailchimp',
    name: 'MailChimp',
    description: 'Email marketing and marketing automation platform.',
    tags: ['Widgets', 'Feedback Forms and Surveys', 'Marketing Automation', 'Email Marketing'],
    liveSites: 1052949,
    indianSites: 9049,
  },
  {
    slug: 'joomla',
    name: 'Joomla!',
    description: 'Open-source content management system.',
    tags: ['Content Management System', 'Open Source'],
    liveSites: 1176000,
    indianSites: 5292,
  },
  {
    slug: 'hubspot',
    name: 'Hubspot',
    description: 'CRM, marketing automation, and inbound marketing platform.',
    tags: ['Analytics and Tracking', 'CRM', 'Marketing Automation', 'Lead Generation', 'Inbound Marketing'],
    liveSites: 755955,
    indianSites: 6614,
  },
  {
    slug: 'laravel',
    name: 'Laravel',
    description: 'Open-source PHP framework for modern web applications.',
    tags: ['Frameworks'],
    liveSites: 682330,
    indianSites: 20432,
  },
  {
    slug: 'new-relic',
    name: 'New Relic',
    description: 'Application performance monitoring and site optimization.',
    tags: ['Analytics and Tracking', 'Application Performance', 'Site Optimization', 'Audience Measurement'],
    liveSites: 683884,
    indianSites: 4595,
  },
  {
    slug: 'ruby-on-rails',
    name: 'Ruby on Rails',
    description: 'Ruby web application framework for rapid development.',
    tags: ['Frameworks'],
    liveSites: 612899,
    indianSites: 4995,
  },
  {
    slug: 'drupal',
    name: 'Drupal',
    description: 'Open-source content management system for complex sites.',
    tags: ['Content Management System', 'Open Source'],
    liveSites: 686000,
    indianSites: 5910,
  },
  {
    slug: 'salesforce',
    name: 'Salesforce',
    description: 'CRM and business management software with marketing automation.',
    tags: ['Analytics and Tracking', 'CRM', 'Marketing Automation', 'Cloud Management', 'Business Management Software'],
    liveSites: 387117,
    indianSites: 2150,
  },
  {
    slug: 'zendesk',
    name: 'Zendesk',
    description: 'Customer service management and customer engagement platform.',
    tags: ['Email Hosting Providers', 'Customer Service Management', 'API Services', 'Collaboration Platform', 'Customer Engagement'],
    liveSites: 397472,
    indianSites: 831,
  },
  {
    slug: 'optimizely',
    name: 'Optimizely',
    description: 'Feature management, growth marketing, and personalization platform.',
    tags: ['Analytics and Tracking', 'Feature Management', 'Growth Marketing', 'Marketing Planning', 'Personalization'],
    liveSites: 228158,
    indianSites: 236,
  },
  {
    slug: 'opencart',
    name: 'OpenCart',
    description: 'Open-source, multi-channel eCommerce platform.',
    tags: ['eCommerce', 'Multi-Channel', 'Open Source'],
    liveSites: 196472,
    indianSites: 2665,
  },
  {
    slug: 'prestashop',
    name: 'PrestaShop',
    description: 'Open-source eCommerce platform.',
    tags: ['eCommerce', 'Open Source'],
    liveSites: 191897,
    indianSites: 486,
  },
  {
    slug: 'magento',
    name: 'Magento',
    description: 'Open-source and enterprise eCommerce platform.',
    tags: ['eCommerce', 'Open Source', 'Hosted Solution', 'Enterprise', 'SMB Solution'],
    liveSites: 161262,
    indianSites: 1632,
  },
  {
    slug: 'adobe-experience-manager',
    name: 'Adobe Experience Manager',
    description: 'Enterprise content management and digital experience platform.',
    tags: ['Content Management System', 'Enterprise', 'Mobile', 'Content Management', 'Digital Experience Platform'],
    liveSites: 166558,
    indianSites: 1751,
  },
  {
    slug: 'omniture-sitecatalyst',
    name: 'Omniture SiteCatalyst',
    description: 'Web analytics, site optimization, and user behavior analytics.',
    tags: ['Analytics and Tracking', 'Site Optimization', 'Web Analytics', 'Business Intelligence and Reporting', 'User Behavior Analytics'],
    liveSites: 168803,
    indianSites: 638,
  },
  {
    slug: 'adroll',
    name: 'AdRoll',
    description: 'Ad network with retargeting and dynamic creative optimization.',
    tags: ['Advertising', 'Ad Network', 'Retargeting / Remarketing', 'Dynamic Creative Optimization', 'Ad Server'],
    liveSites: 119657,
    indianSites: 791,
  },
  {
    slug: 'magento-2',
    name: 'Magento 2',
    description: 'Next-generation Magento eCommerce platform.',
    tags: ['eCommerce', 'Non Platform'],
    liveSites: 118209,
    indianSites: 1123,
  },
  {
    slug: 'taboola',
    name: 'Taboola',
    description: 'Content curation, ad network, and digital video ads.',
    tags: ['Advertising', 'Content Curation', 'Digital Video Ads', 'Ad Network', 'Contextual Advertising'],
    liveSites: 71772,
    indianSites: 1598,
  },
  {
    slug: 'pardot',
    name: 'Pardot',
    description: 'B2B marketing automation, lead generation, and A/B testing.',
    tags: ['Analytics and Tracking', 'Marketing Automation', 'Lead Generation', 'Personalization', 'A/B Testing'],
    liveSites: 61318,
    indianSites: 215,
  },
  {
    slug: 'bigcommerce',
    name: 'BigCommerce',
    description: 'Hosted, multi-channel eCommerce and online store builder.',
    tags: ['eCommerce', 'Hosted Solution', 'Multi-Channel', 'Mobile Commerce Platform', 'Online Store Builder'],
    liveSites: 50073,
    indianSites: 70,
  },
  {
    slug: 'marketo',
    name: 'Marketo',
    description: 'Marketing automation, lead generation, and account based marketing.',
    tags: ['Analytics and Tracking', 'Marketing Automation', 'Lead Generation', 'Sales Enablement', 'Account Based Marketing'],
    liveSites: 36287,
    indianSites: 305,
  },
  {
    slug: 'sitecore-cms',
    name: 'Sitecore CMS',
    description: 'Enterprise content management and digital experience platform.',
    tags: ['Content Management System', 'Enterprise', 'eCommerce Enabled', 'Content Management', 'Digital Experience Platform'],
    liveSites: 29759,
    indianSites: 1209,
  },
  {
    slug: 'infusionsoft',
    name: 'Infusionsoft',
    description: 'CRM, marketing automation, SMS, and email marketing.',
    tags: ['Analytics and Tracking', 'CRM', 'Marketing Automation', 'SMS Marketing', 'Email Marketing'],
    liveSites: 22946,
    indianSites: 23,
  },
  {
    slug: 'oscommerce',
    name: 'osCommerce',
    description: 'Open-source eCommerce platform.',
    tags: ['eCommerce', 'Open Source'],
    liveSites: 21481,
    indianSites: 122,
  },
  {
    slug: 'demandware',
    name: 'Demandware',
    description: 'Enterprise omnichannel commerce platform.',
    tags: ['eCommerce', 'Enterprise', 'Hosted Solution', 'Multi-Channel', 'Omnichannel Commerce'],
    liveSites: 18648,
    indianSites: 62,
  },
  {
    slug: 'liferay',
    name: 'Liferay',
    description: 'Enterprise community CMS and intranet solutions.',
    tags: ['Content Management System', 'Enterprise', 'Community CMS', 'Digital Experience Platform', 'Intranet Solutions'],
    liveSites: 16879,
    indianSites: 142,
  },
  {
    slug: 'eloqua',
    name: 'Eloqua',
    description: 'B2B marketing, A/B testing, marketing automation, and lead generation.',
    tags: ['Analytics and Tracking', 'B2B Marketing', 'A/B Testing', 'Marketing Automation', 'Lead Generation'],
    liveSites: 16014,
    indianSites: 50,
  },
  {
    slug: 'adobe-cq',
    name: 'Adobe CQ',
    description: 'Enterprise content management and digital experience platform.',
    tags: ['Content Management System', 'eCommerce Enabled', 'Enterprise', 'Content Management', 'Digital Experience Platform'],
    liveSites: 11887,
    indianSites: 65,
  },
  {
    slug: 'oracle-commerce',
    name: 'Oracle Commerce',
    description: 'Enterprise omnichannel commerce platform.',
    tags: ['eCommerce', 'Enterprise', 'Multi-Channel', 'Hosted Solution', 'Omnichannel Commerce'],
    liveSites: 9085,
    indianSites: 30,
  },
  {
    slug: 'magento-19',
    name: 'Magento 1.9',
    description: 'Magento 1.9 generation eCommerce platform.',
    tags: ['eCommerce', 'Non Platform'],
    liveSites: 9867,
    indianSites: 111,
  },
  {
    slug: 'volusion',
    name: 'Volusion',
    description: 'Hosted eCommerce with merchandising platform.',
    tags: ['eCommerce', 'Hosted Solution', 'SMB Solution', 'Online Store Builder', 'Merchandising Platform'],
    liveSites: 5849,
    indianSites: 11,
  },
  {
    slug: 'revcontent',
    name: 'RevContent',
    description: 'Content curation and contextual advertising network.',
    tags: ['Advertising', 'Content Curation', 'Contextual Advertising'],
    liveSites: 6167,
    indianSites: 17,
  },
  {
    slug: 'umbraco',
    name: 'Umbraco',
    description: 'Agency-friendly content management with website hosting.',
    tags: ['Content Management System', 'Website Hosting', 'Workflow Automation', 'Agency', 'Content Management'],
    liveSites: 6403,
    indianSites: 19,
  },
  {
    slug: 'rackspace',
    name: 'Rackspace',
    description: 'US dedicated and cloud hosting provider.',
    tags: ['Web Hosting Providers', 'US hosting', 'Dedicated Hosting'],
    liveSites: 252546,
    indianSites: 494,
  },
  {
    slug: 'magento-enterprise',
    name: 'Magento Enterprise',
    description: 'Enterprise online store builder and hosted eCommerce solution.',
    tags: ['eCommerce', 'Enterprise', 'Online Store Builder', 'CMS eCommerce Integration', 'Hosted Solution'],
    liveSites: 4931,
    indianSites: 24,
  },
  {
    slug: 'magento-17',
    name: 'Magento 1.7',
    description: 'Magento 1.7 generation eCommerce platform.',
    tags: ['eCommerce', 'Non Platform'],
    liveSites: 1048,
    indianSites: 7,
  },
  {
    slug: 'zen-cart',
    name: 'Zen Cart',
    description: 'Open-source eCommerce platform.',
    tags: ['eCommerce', 'Open Source'],
    liveSites: 19766,
    indianSites: 61,
  },
];

// Technology group filter — the category taxonomies shown on the trends page.
export const TECH_GROUPS = [
  {
    id: 'advertising',
    name: 'All Advertising',
    description: 'Advertising networks, ad servers, and programmatic technologies.',
    tags: [
      'Ad Server', 'Dynamic Creative Optimization', 'Ad Exchange', 'Ad Network', 'Retargeting / Remarketing',
      'Demand-side Platform', 'Digital Video Ads', 'Affiliate Programs', 'Ad Analytics', 'Search',
      'Audience Targeting', 'Multi-Channel', 'Contextual Advertising', 'Content Curation', 'Local Ads',
      'Cookie Alternative', 'Mobile', 'Data Management Platform', 'Header Bidding', 'Ad Blocking',
      'Fraud Prevention', 'ads txt', 'Adult', 'Bitcoin', 'Seller JSON',
    ],
  },
  {
    id: 'agency',
    name: 'All Agency',
    description: 'Web design and digital agencies by country of operation.',
    tags: [
      'Albanian Agency', 'Algerian Agency', 'Andorran Agency', 'Anguillan Agency', 'Antiguan Agency',
      'Argentinian Agency', 'Armenian Agency', 'Aruban Agency', 'Australian Agency', 'Austrian Agency',
      'Azerbaijani Agency', 'Bahamian Agency', 'Bahraini Agency', 'Belarusian Agency', 'Belgian Agency',
      'Belizean Agency', 'Bengali Agency', 'Bermudan Agency', 'Bhutanese Agency', 'Bolivian Agency',
      'Bosnian Agency', 'Botswanan Agency', 'Brazilian Agency', 'British Virgin Island Agency',
      'Bulgarian Agency', 'Burmese Agency', 'Cabo Verdean Agency', 'Cambodian Agency', 'Cameroonian Agency',
      'Canadian Agency', 'Caymanian Agency', 'Channel Island Agency', 'Chilean Agency', 'Chinese Agency',
      'Coco Islander Agency', 'Congolese Agency', 'Costa Rican Agency', 'Croatian Agency', 'Cypriot Agency',
      'Czech Agency', 'Danish Agency', 'Dominican Agency', 'Dutch Agency', 'Ecuadorian Agency',
      'Egyptian Agency', 'Emirati Agency', 'Estonian Agency', 'Ethiopian Agency', 'Faroese Agency',
      'Fijian Agency', 'Finnish Agency', 'French Agency', 'Gambian Agency', 'Georgian Agency',
      'German Agency', 'Ghanaian Agency', 'Gibraltar Agency', 'Greek Agency', 'Greenlandic Agency',
      'Grenadian Agency', 'Guatemalan Agency', 'Healthcare', 'Honduran Agency', 'Hong Kong Agency',
      'Hungarian Agency', 'Icelandic Agency', 'Indian Agency', 'Indonesian Agency', 'Irish Agency',
      'Israeli Agency', 'Italian Agency', 'Jamaican Agency', 'Japan Agency', 'Jordanian Agency',
      'Kazakh Agency', 'Kenyan Agency', 'Kuwaiti Agency', 'Latvian Agency', 'Lebanese Agency',
      'Libyan Agency', 'Liechtensteiner Agency', 'Lithuanian Agency', 'Luxembourg Agency',
      'Macedonian Agency', 'Mahoran Agency', 'Malagasy Agency', 'Malaysian Agency', 'Maltese Agency',
      'Manx Agency', 'Marshallese Agency', 'Martiniquais Agency', 'Mauritian Agency', 'Mexican Agency',
      'Moldovan Agency', 'Montserratian Agency', 'Moroccan Agency', 'Mozambican Agency', 'Namibian Agency',
      'Nepalese Agency', 'New Zealand Agency', 'Nicaraguan Agency', 'Nigerian Agency', 'Niuean Agency',
      'Norwegian Agency', 'Pakistani Agency', 'Palestinian Agency', 'Panamanian Agency', 'Paraguayan Agency',
      'Persian Agency', 'Peruvian Agency', 'Philippine Agency', 'Polish Agency', 'Portuguese Agency',
      'Puerto Rican Agency', 'Qatari Agency', 'Real Estate', 'Reunion Islander Agency', 'Romanian Agency',
      'Russian Agency', 'Salvadoran Agency', 'Sammarinese Agency', 'Samoan Agency', 'Sao Tomeian Agency',
      'Saudi Arabian Agency', 'Senegalese Agency', 'Serbian Agency', 'Singaporean Agency', 'Slovak Agency',
      'Slovenian Agency', 'Somali Agency', 'South African Agency', 'South Korean Agency', 'Spanish Agency',
      'Sri Lankan Agency', 'Sudanese Agency', 'Surinamian Agency', 'Swedish Agency', 'Swiss Agency',
      'Taiwaniese Agency', 'Tanzanian Agency', 'Thai Agency', 'Togolese Agency', 'Tongan Agency',
      'Trinidadian Agency', 'Tunisian Agency', 'Turkish Agency', 'Turkmen Agency', 'Turks and Caicos Island Agency',
      'Ugandan Agency', 'UK Agency', 'Ukrainian Agency', 'Uruguayan Agency', 'US Agency',
      'Uzbekistani Agency', 'Vanuatuan Agency', 'Venezuelan Agency', 'Vietnamese Agency', 'Zambian Agency',
      'Zimbabwean Agency',
    ],
  },
  {
    id: 'analytics',
    name: 'All Analytics and Tracking',
    description: 'Web analytics, marketing automation, and customer data technologies.',
    tags: [
      'A/B Testing', 'Advertiser Tracking', 'Marketing Automation', 'Data Management Platform',
      'Cart Abandonment', 'Conversion Optimization', 'Site Optimization', 'Fraud Prevention', 'Tag Management',
      'CRM', 'Feedback Forms and Surveys', 'Error Tracking', 'Product Recommendations', 'Personalization',
      'Visitor Count Tracking', 'Social Management', 'Lead Generation', 'Audience Measurement',
      'Application Performance', 'Retargeting / Remarketing', 'AI', 'Content Experience Platform',
      'Real Estate', 'Conversion Tracking', 'Call Tracking', 'Content Management', 'Mobile',
      'Customer Data Platform', 'Account Based Marketing', 'Ad Management Platform', 'Ad Pixel Management',
      'Ad Targeting', 'Ad Technology', 'Advocate Marketing', 'Affiliate Marketing', 'Agency Management',
      'AI Business Automation', 'AI for Real Estate', 'AI for UX Analytics', 'AI Marketing Automation',
      'AI Sales Automation', 'AI SEO', 'API Integration Platform', 'Association Management', 'Automation',
      'Automotive Industry Analytics', 'Automotive Marketing', 'Automotive Services Software', 'B2B Data',
      'B2B Marketing', 'Behavioral Messaging', 'Big Data Analytics', 'Blog Analytics', 'Booking Management',
      'Bot Management', 'Brand Management', 'Brand Monitoring', 'Business Automation Platform',
      'Business Intelligence and Reporting', 'Business Management Software', 'Business Process Management',
      'Call Center Analytics', 'Call Management', 'Callback Widget', 'Campaign Performance Analytics',
      'Channel Marketing', 'Checkout Optimization', 'Church Management', 'Churn Prediction',
      'Click Fraud Prevention', 'Cloud Management', 'Code Quality', 'Communication Automation',
      'Communications Analytics', 'Community Management', 'Competitive Intelligence', 'Construction Technology',
      'Consumer Insights', 'Consumer Research', 'Contact Center Software', 'Contact Management',
      'Content Analytics', 'Content Marketing', 'Contest Marketing', 'Conversational AI',
      'Conversational Sales', 'Coupon and Promotion Management', 'Creative Automation',
      'Cross-Channel Advertising Analytics', 'Customer Acquisition', 'Customer Communication Platform',
      'Customer Data Infrastructure', 'Customer Engagement', 'Customer Experience Management',
      'Customer Journey Analytics', 'Customer Lifecycle Management', 'Customer Retention',
      'Customer Segmentation', 'Customer Sentiment Analysis', 'Customer Service Automation',
      'Customer Service Software', 'Customer Success', 'Cybersecurity Intelligence', 'Data Collection Platform',
      'Data Driven Marketing', 'Data Enrichment', 'Data Integration', 'Data Intelligence',
      'Data Observability', 'Data Prospecting', 'Data Science Platforms', 'Data Unification',
      'Data Visualization', 'Developer Tools', 'Device Fingerprinting', 'Digital Accessibility',
      'Digital Asset Management', 'Digital Customer Experience', 'Digital Marketing Suite',
      'Digital Presence Management', 'Direct Response Marketing', 'DTC Ecommerce Solutions', 'Dynamic Content',
      'eCommerce AI Solutions', 'eCommerce Analytics', 'eCommerce CRM', 'eCommerce Intelligence',
      'eCommerce Marketing', 'eCommerce Merchandising', 'eCommerce Optimization', 'eCommerce Platform',
      'eCommerce Security', 'Email Marketing', 'Enterprise Analytics', 'Enterprise Resource Planning',
      'Event Management', 'Event Marketing', 'Exit Intent Marketing', 'Experience Management',
      'Experimentation Platform', 'Fashion Technology', 'Feature Management', 'Financial Analytics',
      'Financial Services Technology', 'First-Party Data Management', 'Form Builder', 'Fundraising Management',
      'Gamification', 'Geo-Targeting', 'Growth Marketing', 'Guided Selling', 'Healthcare Marketing',
      'Healthcare Practice Management', 'Healthcare Technology', 'Heatmap Analytics', 'Hospitality Management',
      'Identity Resolution', 'Inbound Marketing', 'Incentive Programs', 'Influencer Marketing Management',
      'Infrastructure Monitoring', 'Insurance Technology', 'Interactive Content', 'Internal Communications',
      'International Marketing', 'Inventory Management', 'IT Operations Management', 'IT Service Management',
      'Keyword Research', 'Landing Page Builder', 'Lead Management', 'Lead Nurturing', 'Lead Qualification',
      'Lead Scoring', 'Lease Management', 'Leasing Automation', 'Live Chat', 'Local Business Management',
      'Local Marketing', 'Local SEO', 'Location Analytics', 'Log Analytics', 'Loyalty Management',
      'Market Intelligence', 'Market Research', 'Marketing Agency Software', 'Marketing Attribution',
      'Marketing Data Integration', 'Marketing Planning', 'Marketplace Platform', 'Media Analytics',
      'Messaging Marketing', 'Mobile Marketing', 'Monetization Platform', 'Multi-channel Sales Platform',
      'Network Security', 'Non-Profit Management Software', 'NPS and Customer Satisfaction',
      'Offline Marketing', 'Omnichannel Communication', 'Omnichannel Marketing', 'On-site Engagement',
      'On-site Search', 'Open Source Analytics', 'Opportunity Management', 'Organic Growth Marketing',
      'Partner Relationship Management', 'Payment Analytics', 'Performance Marketing', 'Performance Tracking',
      'Pop-up Marketing', 'Post-Purchase Engagement', 'Predictive Analytics', 'Pricing Optimization',
      'Privacy Compliance', 'Privacy-First Analytics', 'Product Advertising', 'Product Analytics',
      'Product Communication', 'Product Customization Platform', 'Product Feed Management',
      'Product Information Management', 'Product Led Growth', 'Product Research', 'Product Showcase Platform',
      'Professional Services Automation', 'Profit Optimization', 'Programmatic Advertising',
      'Project Management', 'Property Management Software', 'Real Estate Software', 'Real User Monitoring',
      'Real-time Analytics', 'Real-time Data Platform', 'Real-time Engagement', 'Recruitment Analytics',
      'Recruitment Technology', 'Referral Marketing', 'Reservation Analytics', 'Retail Intelligence',
      'Returns Management', 'Revenue Intelligence', 'Revenue Operations', 'Review Management', 'SaaS Analytics',
      'Sales Automation', 'Sales Enablement', 'Sales Engagement Platform', 'Sales Funnel Management',
      'Sales Intelligence', 'Sales Outreach', 'Sales Promotion', 'Sales Scheduling', 'SEO and SEM Analytics',
      'SERP Analysis', 'Server-Side Tagging', 'Session Replay', 'Shopify Apps', 'SMS Marketing',
      'Social Commerce', 'Social Media Advertising', 'Social Media Analytics', 'Social Media Management',
      'Social Proof', 'Software Testing', 'Subscription Management', 'Supply Chain Analytics',
      'Team Collaboration', 'Threat Protection', 'UI/UX Testing', 'Unified Marketing Platform',
      'Upsell and Cross-sell', 'Uptime Monitoring', 'User Acquisition', 'User Behavior Analytics',
      'User Generated Content', 'User Onboarding', 'UX Automation', 'Video Analytics',
      'Video Engagement Platform', 'Visual Feedback', 'Web Analytics', 'Web Governance',
      'Web Push Notifications', 'Web Security', 'Website Builder', 'Website Performance Monitoring',
      'Website Visitor Identification',
    ],
  },
  {
    id: 'media',
    name: 'All Audio / Video Media',
    description: 'Online video platforms, players, and streaming technologies.',
    tags: [
      'Online Video Platform', 'Live Stream / Webcast', 'Video Analytics', 'Digital Video Ads',
      'Video Players', 'Enterprise', 'Social Video Platform',
    ],
  },
  {
    id: 'cms',
    name: 'All Content Management System',
    description: 'Content management, publishing, and website building platforms.',
    tags: [
      'Open Source', 'Forum Software', 'Wiki', 'Community CMS', 'Simple Website Builder', 'Hosted Solution',
      'eCommerce Enabled', 'Landing Page', 'Social Management', 'Enterprise', 'Financial', 'Blog', 'Mobile',
      'Learning Management System', 'Automotive', 'Headless', 'Non Profit', 'Agency', 'Real Estate',
      'Ticketing System', 'Healthcare', 'Job Board', 'Access Management', 'Accounting Software',
      'Advocacy Platform', 'Agriculture Technology', 'AI Development Platform', 'AI-Powered Solutions',
      'Alumni Engagement Platform', 'Analytics Platform', 'API Management', 'App Builder',
      'Applicant Tracking System', 'Arts and Culture Technology', 'Association Management',
      'Automotive Dealership Management', 'Banking Technology', 'Beauty and Wellness Management',
      'Benefits Administration', 'Billing And Payment Solutions', 'Booking Management', 'Brand Management',
      'Bridal Technology', 'Business Automation', 'Business Intelligence', 'Career Readiness',
      'Catalog Management', 'Channel Management', 'Childcare Management', 'Church Management Software',
      'Citizen Engagement Platform', 'Client Communication Platform', 'Cloud Platform', 'Club Management',
      'Coaching and Mentoring Platform', 'Collaboration Software', 'College Admissions',
      'Commercial Real Estate', 'Community Engagement Platform', 'Compliance Management',
      'Conference Management', 'Construction Technology', 'Contact Center Software', 'Content Management',
      'Conversion Rate Optimization', 'Creative Business Management', 'Creator Economy Platform',
      'Custom Application Development', 'Customer Education', 'Customer Experience Management',
      'Customer Onboarding', 'CRM', 'Customer Support Software', 'Data Management', 'Dealership Technology',
      'Dental Technology', 'Design Collaboration', 'Developer Tools', 'Digital Asset Management',
      'Digital Experience Platform', 'Digital Publishing Tool', 'Directory Software', 'Document Management',
      'Documentation Platform', 'Education Technology', 'Electronic Health Records', 'Email Marketing',
      'Embedded Communities', 'Employee Engagement', 'Employer Branding', 'Enterprise Resource Planning',
      'Event Management', 'Facilities Management', 'Field Service Management', 'Fitness and Wellness Technology',
      'Floral Technology', 'Food Ordering System', 'Franchise Management', 'Frontline Workforce Management',
      'Fundraising Software', 'Gaming Community Platform', 'Government Technology', 'Grants Management',
      'Health and Wellness Management', 'Higher Education Technology', 'Hospitality Technology',
      'Hotel Management', 'Human Capital Management', 'Human Resources Management System',
      'Insurance Technology', 'Integrated Business Management', 'Integration Platform',
      'Interactive Content Platform', 'Internal Communications', 'Internal Tools Platform',
      'Intranet Solutions', 'Inventory Management', 'Investment Management', 'Investor Relations',
      'Invoice Management', 'IT Asset Management', 'IT Operations Management', 'IT Service Management',
      'Journalism Technology', 'Knowledge Base Software', 'Knowledge Management', 'Lead Generation',
      'Legal Technology', 'Listing Management', 'Local Business Solutions', 'Low Code No Code Platform',
      'Marketing Funnel Builder', 'Marketing Platform', 'Marketplace Platform', 'Media Technology',
      'Membership Management', 'Mental Health Technology', 'Mobile Experience Platform',
      'Monitoring Software', 'Mortgage Technology', 'Multisite Management', 'Newsletter Platform',
      'Online Course Platform', 'Operations Management', 'Order Fulfillment',
      'Partner Relationship Management', 'Patient Engagement', 'Payroll Management',
      'Performance Management', 'Personalization Engine', 'Pet Care Management', 'Photo Management Software',
      'Photography Business Management', 'Point Of Sale Systems', 'Political Technology',
      'Portal Management', 'Portfolio Management', 'Practice Management', 'Predictive Analytics',
      'Product Information Management', 'Product Management', 'Product Visualization',
      'Professional Services Automation', 'Project Management', 'Property Management',
      'Proposal Management', 'PropTech', 'Public Relations Technology', 'Public Sector Solutions',
      'Publishing Platform', 'QandA Platform', 'Real Estate Marketing', 'Recreation Management',
      'Recruitment Technology', 'Registration Management', 'Religious Technology', 'Resident Engagement',
      'Restaurant Technology', 'Retail Technology', 'Risk Management', 'Sales Management',
      'Salon and Spa Management', 'Scheduling Software', 'School Communications', 'School Management',
      'Search Engine Optimization', 'Security Compliance', 'Self Service Platform', 'Service Management',
      'Sports and Entertainment Technology', 'Sports Management', 'Staffing Management',
      'Static Site Generation', 'Student Enrollment Management', 'Student Information System',
      'Studio Management', 'Subscription Management', 'Supply Chain Management', 'Talent Management',
      'Team Management', 'Technical Documentation', 'Telehealth', 'Time Tracking', 'Tour Operator Software',
      'Training Management', 'Transaction Management', 'Transport Technology', 'Travel and Tourism Technology',
      'Treasury Management', 'UI/UX Design Tool', 'User Generated Content', 'Veterinary Technology',
      'Video Platform', 'Virtual Event Platform', 'Visual Editor', 'Volunteer Management',
      'Web Development', 'Website Hosting', 'Website Monitoring', 'Website Traffic Generation',
      'White Label Platform', 'Workflow Automation',
    ],
  },
];

export function allTechSlugs() {
  return [...TECH_DIRECTORY, ...SPOTLIGHT_TECHNOLOGIES].map((t) => t.slug);
}

export function getTechBySlug(slug) {
  return TECH_DIRECTORY.find((t) => t.slug === slug) || SPOTLIGHT_TECHNOLOGIES.find((t) => t.slug === slug) || null;
}

export function countrySites(tech, code) {
  if (code === 'IN') return tech.indianSites;
  if (code === 'WW') return tech.liveSites;
  const mult = COUNTRY_MULTIPLIERS[code];
  if (!mult) return null;
  return Math.round(tech.liveSites * mult);
}

export function countryLabel(code) {
  const c = COUNTRIES.find((c) => c.code === code);
  return c ? `${c.flag} ${c.name}` : 'Worldwide';
}

export function relatedTechs(tech, limit = 4) {
  const primary = tech.tags[0];
  return TECH_DIRECTORY.filter((t) => t.slug !== tech.slug && t.tags.includes(primary)).slice(0, limit);
}

export function allTechTags() {
  return [...new Set(TECH_DIRECTORY.flatMap((t) => t.tags))].sort();
}

export function totalLiveSites() {
  return TECH_DIRECTORY.reduce((sum, t) => sum + t.liveSites, 0);
}
