  'API Gateway': 'infra',
  'API Management': 'frontend',
  'Accessibility Testing': 'frontend',
  'Accordion Component': 'frontend',
  'Analytics': 'frontend',
  'Animation Library': 'frontend',
  'Artifact Repository': 'infra',
  'Audio Player': 'frontend',
  'Backup Service': 'infra',
  'Billing': 'frontend',
  'Blockchain': 'backend',
  'Booking': 'backend',
  'Browser Testing': 'frontend',
  'Build Tool': 'frontend',
  'CAPTCHA': 'backend',
  'CDN': 'infra',
  'CI/CD': 'frontend',
  'CMS': 'backend',
  'CRM': 'backend',
  'CSS Framework': 'frontend',
  'CSS Framework Plugin': 'frontend',
  'CSS Tool': 'frontend',
  'CSS-in-JS': 'frontend',
  'Cache': 'backend',
  'Capacity Planning': 'infra',
  'Carousel/Slider': 'frontend',
  'Changelog': 'backend',
  'Chaos Engineering': 'infra',
  'Chart Library': 'frontend',
  'Chatbot': 'backend',
  'Cloud': 'infra',
  'Cloud Cost Management': 'infra',
  'Code Coverage': 'frontend',
  'Code Review': 'frontend',
  'Collaboration Tool': 'infra',
  'Color Picker': 'frontend',
  'Compliance Tool': 'infra',
  'Container': 'infra',
  'Container Registry': 'infra',
  'DNS': 'infra',
  'Data Integration': 'frontend',
  'Data Loss Prevention': 'frontend',
  'Data Table': 'frontend',
  'Data Warehouse': 'frontend',
  'Database': 'backend',
  'Database Client': 'backend',
  'Date Library': 'frontend',
  'Debugging Tools': 'infra',
  'Dependency Scanning': 'infra',
  'Design': 'frontend',
  'Diagramming': 'infra',
  'Digital Whiteboard': 'frontend',
  'Directory Service': 'infra',
  'Disaster Recovery': 'infra',
  'Distributed Tracing': 'infra',
  'Document Management': 'frontend',
  'Drag and Drop': 'frontend',
  'E-Signature': 'frontend',
  'E-commerce': 'frontend',
  'ETL/Data Pipeline': 'infra',
  'Edge Runtime': 'infra',
  'Endpoint Detection': 'frontend',
  'Event Emitter': 'frontend',
  'Experimentation': 'infra',
  'Extended Detection': 'frontend',
  'Feature Flags': 'frontend',
  'Feedback': 'backend',
  'File Upload': 'frontend',
  'FinOps': 'infra',
  'Font Library': 'frontend',
  'Fonts': 'frontend',
  'Form Library': 'backend',
  'Form Validator': 'backend',
  'Forms': 'backend',
  'Frontend': 'frontend',
  'Frontend Framework': 'frontend',
  'GitOps': 'infra',
  'GraphQL Client': 'frontend',
  'HTTP Client': 'frontend',
  'Hardware Security Module': 'infra',
  'Headless CMS': 'backend',
  'Help Desk': 'frontend',
  'Hosting': 'infra',
  'Icon Library': 'frontend',
  'Identity Provider': 'frontend',
  'Image Gallery': 'frontend',
  'Images': 'frontend',
  'Incident Management': 'infra',
  'Infra': 'infra',
  'Infrastructure Provisioning': 'infra',
  'Integration Platform': 'backend',
  'JavaScript Library': 'frontend',
  'Key Management': 'frontend',
  'Knowledge Base': 'infra',
  'LMS': 'backend',
  'Lazy Loading': 'frontend',
  'License Scanning': 'infra',
  'Live Chat': 'frontend',
  'Load Balancer': 'frontend',
  'Load Testing': 'frontend',
  'Localization Tools': 'infra',
  'Log Aggregation': 'frontend',
  'Logging': 'infra',
  'Map Library': 'frontend',
  'Maps': 'frontend',
  'Markdown Library': 'frontend',
  'Message Queue': 'frontend',
  'Meta Framework': 'frontend',
  'Metrics': 'infra',
  'Mobile Framework': 'frontend',
  'Modal Library': 'frontend',
  'Monitoring': 'infra',
  'Network Monitoring': 'infra',
  'Newsletter': 'backend',
  'ORM': 'backend',
  'Object Storage': 'frontend',
  'Observability': 'infra',
  'On-Call': 'frontend',
  'Orchestration': 'infra',
  'PDF Library': 'frontend',
  'PKI/Certificate Management': 'infra',
  'Payment': 'backend',
  'Performance Testing': 'backend',
  'Policy Engine': 'infra',
  'Profiling': 'infra',
  'Project Management': 'frontend',
  'Provisioning': 'infra',
  'Resource Management': 'frontend',
  'Reverse Proxy': 'frontend',
  'Rich Text Editor': 'frontend',
  'Robotic Process Automation': 'frontend',
  'Router Library': 'frontend',
  'SIEM': 'infra',
  'SOAR': 'infra',
  'SSL/TLS': 'infra',
  'SSR Framework': 'frontend',
  'Schema Validation': 'frontend',
  'Screen Sharing': 'frontend',
  'Search Engine': 'frontend',
  'Secret Vault': 'infra',
  'Security': 'infra',
  'Security Scanning': 'infra',
  'Select Component': 'frontend',
  'Serverless': 'backend',
  'Service Discovery': 'frontend',
  'Service Mesh': 'frontend',
  'Service Registry': 'infra',
  'State Management': 'frontend',
  'Static Analysis': 'frontend',
  'Status': 'frontend',
  'Syntax Highlighter': 'frontend',
  'Tabs Component': 'frontend',
  'Tag Management': 'frontend',
  'Testing Library': 'frontend',
  'Toast Library': 'frontend',
  'Tooltip Library': 'frontend',
  'Translation': 'frontend',
  'Translation Memory': 'frontend',
  'UI Component Library': 'frontend',
  'UUID Generator': 'frontend',
  'Utility Library': 'frontend',
  'Video': 'frontend',
  'Video Conferencing': 'frontend',
  'Video Player': 'frontend',
  'Virtual Scroll': 'frontend',
  'Visual Testing': 'frontend',
  'Vulnerability Scanner': 'infra',
  'WAF': 'infra',
  'Weather': 'frontend',
  'WebGL Library': 'frontend',
  'Whiteboarding': 'infra',
  'Workflow Automation': 'frontend',
  'Zero Trust': 'frontend',
  'ab_testing': 'backend',
  'analytics_platform': 'backend',
  'api_protocol': 'backend',
  'authentication': 'backend',
  'blockchain': 'backend',
  'booking': 'backend',
  'business_intelligence': 'backend',
  'caching': 'frontend',
  'captcha': 'backend',
  'cdn_service': 'infra',
  'changelog': 'backend',
  'chatbot': 'backend',
  'ci_cd': 'infra',
  'cicd': 'frontend',
  'cloud_platform': 'backend',
  'cloud_region': 'infra',
  'cms': 'backend',
  'code_editor': 'frontend',
  'container_registry': 'infra',
  'container_tool': 'infra',
  'cookie_consent': 'backend',
  'crm': 'backend',
  'crypto_service': 'backend',
  'data_catalog': 'backend',
  'data_warehouse': 'infra',
  'database': 'backend',
  'design_tool': 'backend',
  'dns_provider': 'infra',
  'doc_platform': 'backend',
  'dotnet_framework': 'frontend',
  'ecommerce': 'backend',
  'elixir_framework': 'frontend',
  'email_service': 'backend',
  'error_tracking': 'frontend',
  'esignature': 'backend',
  'etl_tool': 'infra',
  'experimentation': 'infra',
  'feature_flags': 'infra',
  'feedback_tool': 'backend',
  'file_storage': 'backend',
  'font_service': 'frontend',
  'form_builder': 'backend',
  'forum': 'backend',
  'go_framework': 'frontend',
  'headless_cms': 'backend',
  'heatmap': 'backend',
  'helpdesk': 'backend',
  'hosting_platform': 'backend',
  'i18n Library': 'frontend',
  'i18n Platform': 'backend',
  'image_service': 'backend',
  'invoice': 'backend',
  'iot_platform': 'backend',
  'java_framework': 'frontend',
  'javascript_library': 'frontend',
  'live_chat': 'backend',
  'lms': 'backend',
  'logging': 'infra',
  'map_service': 'frontend',
  'marketing_tool': 'backend',
  'message_queue': 'backend',
  'monitoring': 'infra',
  'newsletter': 'backend',
  'observability': 'infra',
  'onboarding': 'backend',
  'orm': 'backend',
  'payment_processor': 'backend',
  'php_framework': 'frontend',
  'privacy_tool': 'backend',
  'project_management': 'frontend',
  'push_notification': 'frontend',
  'python_framework': 'frontend',
  'ruby_framework': 'frontend',
  'runtime': 'frontend',
  'rust_framework': 'frontend',
  'saas_tool': 'backend',
  'search_engine': 'backend',
  'security_tool': 'infra',
  'server_framework': 'backend',
  'server_fw': 'backend',
  'serverless': 'backend',
  'session_recording': 'backend',
  'sms_service': 'backend',
  'ssl_provider': 'infra',
  'status_page': 'backend',
  'tag_manager': 'backend',
  'template_engine': 'backend',
  'translation_service': 'backend',
  'user_research': 'backend',
  'version_control': 'frontend',
  'video_hosting': 'backend',
  'voice_service': 'backend',
  'waf': 'infra',
  'weather_service': 'frontend',
  'webhook_service': 'backend',
  'wiki': 'backend',